# House Price Prediction Project
 ### 1. Problem Definition (Định nghĩa vấn đề, cho mọi người biết cái project này được dùng để làm gì):
 - Mục tiêu: Dự đoán giá bán của từng căn nhà. Mỗi căn nhà có id và các thuộc tính, dựa vào đó để dự đoán giá bán sao cho gần và chính xác nhất so với giá thực tế.
 ### 2. Feature Selection (Chọn đặc trưng để huấn luyện mô hình máy học):
 - Chọn một vài đặc trưng (cột) trong số các đặc trưng có sẵn mà bạn nghĩ tốt nhất để cho mô hình này dự đoán một cách chính xác nhất
 ### 3. Spliting The Datasets
 #### 3.1 dataset -> X,Y
 - `data` = dataset
 - `X` = `data[features]`
 - `Y` = target variable `SalePrices`
 #### 3.2 X,Y -> X_train, Y_train, X_valid, Y_valid
 ### 4. Training Machine Learning Model 

In [12]:
#Import Librabries
import pandas as pd
import numpy as ny

In [28]:
data = pd.read_csv("./data/train.csv")

In [32]:
data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [34]:
data = pd.read_csv("./data/train.csv", index_col = "Id")

In [36]:
data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [47]:
data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

## 2.Feature Selection

In [57]:
features = ["LotArea","YearBuilt","1stFlrSF","2ndFlrSF","FullBath","BedroomAbvGr","TotRmsAbvGrd"]

## 3.Spliting Dataset into X && Y

In [63]:
X = data[features]
Y = data["SalePrice"]

In [61]:
X.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                   
1      8450       2003       856       854         2             3   
2      9600       1976      1262         0         2             3   
3     11250       2001       920       866         2             3   
4      9550       1915       961       756         1             3   
5     14260       2000      1145      1053         2             4   

    TotRmsAbvGrd  
Id                
1              8  
2              6  
3              6  
4              7  
5              9

In [65]:
Y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

## X,Y -> X_train, Y_train, X_valid, Y_valid

In [75]:
from sklearn.model_selection import train_test_split
X_train, X_valid, Y_train, Y_valid = train_test_split(X,Y,train_size= 0.8, test_size= 0.2, random_state=0)

In [77]:
X_train

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                     
619     11694       2007      1828         0         2             3   
871      6600       1962       894         0         1             2   
93      13360       1921       964         0         1             2   
818     13265       2002      1689         0         2             3   
303     13704       2001      1541         0         2             3   
...       ...        ...       ...       ...       ...           ...   
764      9430       1999      1268      1097         2             3   
836      9600       1950      1067         0         2             2   
1217     8930       1978      1318       584         2             4   
560      3196       2003      1557         0         2             2   
685     16770       1998      1195       644         2             4   

      TotRmsAbvGrd  
Id                  
619              9  
871              5  
93               5  
818              7  
303              6  
...            ...  
764              8  
836              4  
1217             8  
560              7  
685              7  

[1168 rows x 7 columns]

In [79]:
X_train.shape

(1168, 7)

In [81]:
X.shape

(1460, 7)

In [83]:
X_valid.shape

(292, 7)

 ## 4. Training Machine Learning Model 

In [90]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor(random_state=1)

In [94]:
#Fit training data into model
dt_model.fit(X_train, Y_train)

DecisionTreeRegressor(random_state=1)

In [96]:
Y_preds = dt_model.predict(X_valid.head())

In [98]:
Y_preds

array([335000., 140200., 119000., 207500., 112000.])

In [102]:
pd.DataFrame({'Y' : Y_valid.head(),'Y_preds' : Y_preds})

Y   Y_preds
Id                   
530  200624  335000.0
492  133000  140200.0
460  110000  119000.0
280  192000  207500.0
656   88000  112000.0

In [104]:
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor(random_state=1)
rf_model.fit(X_train,Y_train)

RandomForestRegressor(random_state=1)

In [106]:
rf_val_preds = rf_model.predict(X_valid)

In [108]:
rf_val_preds[:5]

array([271690., 155039., 122024., 188915.,  91147.])

### Predict with new input

In [112]:
X_valid.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                    
530    32668       1957      2515         0         3             4   
492     9490       1941       958       620         1             3   
460     7015       1950       979       224         1             3   
280    10005       1977      1156       866         2             4   
656     1680       1971       525       567         1             3   

     TotRmsAbvGrd  
Id                 
530             9  
492             5  
460             5  
280             8  
656             6

In [118]:
rf_model.predict([[6969,2021,1000,800,4,5,8]])

C:\Users\duong\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([206158.4])